name: Pull Request Dispatcher

on:
  issue_comment:
    types:
      - created

jobs:
  slash_command_dispatch:
    name: Slash Command Dispatcher
    runs-on: ubuntu-latest
    permissions:
      pull-request: write
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          commands: |
            test
            help
          permission: maintain
          issue-type: pull-request
          event-type-suffix: -command
